### ISSUE TITLE
Gostaria de pesquisar um cliente por cnpj

### ISSUE THREAD

**Issue by polvoazul** [BoletoSimples/boletosimples-api#5]
Desculpe criar essa issue aqui, mas nao consegui achar algum lugar apropriado no site do boleto simples.
Basicamente eu quero criar um cliente, mas o cnpj dele ja esta criado entao recebo um erro. Porem, no erro nao vem o ID dele e eu nao sei qual eh o ID.
Hoje a unica coisa q eu posso fazer eh buscar todos os usuarios ate encontrar aquele com o cnpj associado para pegar o ID.
Existe alguma forma de pesquisar um usuario por cnpj?
Abs

**Comment by kivanio** [comment]
@polvoazul existe 2 formas recém criadas mas que ainda não estão documentadas na API.
/api/v1/customers/cnpj_cpf?q=00000000000
/api/v1/customers/email?q=customer@example.com

O primeiro endpoint `cnpj_cpf` para buscar pelo CPF ou CNPJ enviando o parâmetro `q`
O segundo endpoint `email ` para buscar pelo email enviando o parâmetro `q`

**Comment by kivanio** [comment]
Atualizado http://api.boletosimples.com.br/reference/v1/customers/

**Comment by polvoazul** [comment]
Maravilha!
Mas acho q achei um bug, na tabela principal da documentacao esta listado como PATCH

**Comment by kivanio** [comment]
Obrigado pelo aviso.
Correção feita.
